config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'personal_data#index'
  resources :personal_data
  resources :employments, only: %i[new create] do
    member do
      post :add_employment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employment.rb
# frozen_string_literal: true

class Employment < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :personal_data

  validates :employer, presence: true
  validates :date_started, presence: true
  validates :date_ended, presence: true
end

app/models/personal_data.rb
# frozen_string_literal: true

class PersonalData < ApplicationRecord # rubocop:disable Style/Documentation
  has_many :employments, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email_address, presence: true, uniqueness: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  def create
    @personalData = PersonalData.find_by(id: employment_params[:personal_data_id])
    employment_params[:employer].each_with_index do |emp, index|
      @employment = Employment.new(employer: emp, date_started: employment_params[:date_started][index], date_ended: employment_params[:date_ended][index])
      @employment.personal_data_id = @personalData.id
      @employment.save
    end

    respond_to do |format|
      format.html { redirect_to personal_datum_path(@personalData) }
    end
  end

  def add_employment
    helpers.fields model: Employment.new do |f|
      render turbo_stream: turbo_stream.append(
        'add-employment',
        partial: 'employments/employment_fields',
        locals: { f: f, first_employment: nil }
      )
    end
  end

  private

  def employment_params
    params.require(:employment).permit(:personal_data_id, employer: [], date_started: [], date_ended: [])
  end
end

app/controllers/personal_data_controller.rb
class PersonalDataController < ApplicationController
  before_action :set_personal_data, only: %i[show update]
  before_action :ensure_frame_response, only: :new

  def index
    @personalData = PersonalData.includes(:employments).all
  end

  def new
    @personalData = PersonalData.new
  end

  def create
    @personalData = PersonalData.new(personal_data_params)
    respond_to do |format|
      if @personalData.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove('personal-data-form') +
                               turbo_stream.update(
                                 'employment-modal',
                                 partial: 'employments/employment_modal',
                                 locals: { personal_data_id: @personalData.id }
                               )
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personalData.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_personal_data
    @personalData = PersonalData.find(params[:id])
  end

  def ensure_frame_response
    return unless Rails.env.development?

    redirect_to root_path unless turbo_frame_request?
  end

  def personal_data_params
    params.require(:personal_data).permit(:first_name, :last_name, :nick_name, :email_address, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/personal_data_helper.rb
module PersonalDataHelper
end

app/views/employments/_employment_fields.html.slim
- border_style = first_employment ? "none" : "1px solid grey"

hr.mb-10(style="border-width: 1px; border-style: #{border_style}; border-color: grey;")
.my-2
  = f.label :employer
  = f.text_field :employer, autocomplete: "off", required: true, name: "employment[employer][]", id: "employerName", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { controller: "employments" }
.my-5
  = f.label :date_started
  = f.date_field :date_started, autocomplete: "off", required: true, name: "employment[date_started][]", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { controller: "employments" }
.my-5
  = f.label :date_ended
  = f.date_field :date_ended, autocomplete: "off", required: true, name: "employment[date_ended][]", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { controller: "employments" }
.mb-12

app/views/employments/_employment_modal.html.slim
.fixed.inset-0.flex.items-center.justify-center.z-50.bg-black.bg-opacity-50.overflow-y-scroll
  .h-full.mt-40.mb-20
    .modal-wrapper.bg-white.p-20.rounded-md
      = render 'employments/form', employment: Employment.new, personal_data_id: personal_data_id

app/views/employments/_form.html.slim
.modal-wrapper.bg-white.p-8.rounded-md
  = form_with(model: employment, url: employments_path, class: "contents", data: { turbo_frame: "_top" } ) do |form|
    = form.hidden_field :personal_data_id, value: personal_data_id
    =render 'employments/employment_fields', f: form, first_employment: :true
    #add-employment
    .inline
      = link_to 'Add Employment', add_employment_employment_path(personal_data_id), class: "rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer", data: { turbo_method: :post }
      = form.submit "Save", id: "saveButton", class: "rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer ml-2"

app/views/layouts/application.html.slim
doctype html
html
  head
    title EmployeeManagement
    meta name="viewport" content="width=device-width,initial-scale=1"
    == csrf_meta_tags
    == csp_meta_tag
    == stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    == stylesheet_link_tag "application", "data-turbo-track": "reload"
    == stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css'
    == javascript_importmap_tags

  body
    main.container.mx-auto.mt-28.px-5
      == turbo_frame_tag "modal"
      == turbo_frame_tag "employment-modal"
      == yield

app/views/personal_data/_form.html.slim
= turbo_frame_tag "personal-data-form" do
  .fixed.inset-0.flex.items-center.justify-center.z-50.bg-black.bg-opacity-50
    .modal-wrapper.bg-white.p-20.rounded-md
      = form_with(model: personal_data, url: personal_data_path, class: "contents", data: { controller: "turbo-modal", turbo_modal_target: "modal" }) do |form|
        = hidden_field_tag :personal_data_id, personal_data.id
        .my-2
          = form.label :first_name
          = form.text_field :first_name, autocomplete: "off", required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", id: "firstName", data: { controller: "personal-data", action: "input->personal-data#validateName", error: "firstNameError", maxLength: 25, name: 'First name' }
          span#firstNameError.text-red-500

        .my-2
          = form.label :last_name
          = form.text_field :last_name, autocomplete: "off", required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", id: "lastName", data: { controller: "personal-data", action: "input->personal-data#validateName", error: "lastNameError", maxLength: 50, name: 'Last name' }
          span#lastNameError.text-red-500

        .my-2
          = form.label :nick_name
          = form.text_field :nick_name, autocomplete: "off", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full"

        .my-2
          = form.label :email_address
          = form.text_field :email_address, id: "email_address", autocomplete: "off", required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { controller: "personal-data", action: "input->personal-data#validateEmail" }
          span#emailError.text-red-500

        .my-5
          = form.label :phone_number
          = form.text_field :phone_number, autocomplete: "off", required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { controller: "personal-data", action: "input->personal-data#validatePhoneNumber" }, id: "phone_number"
          span#phoneNumberError.text-red-500

        .inline.flex
          = form.submit "Save", id: "saveButton", class: "rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer mr-2"
          = button_tag "Cancel", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-green-700 text-white inline-block font-medium cursor-pointer ml-2"

app/views/personal_data/_personal_data.html.slim
- if defined?(personal_data)
  div id="#{dom_id(personal_data)}"

    div.flex.items-center
      strong.block.font-medium.mb-1 First Name:
      span.ml-2 = personal_data.first_name

    div.flex.items-center
      strong.block.font-medium.mb-1 Last Name:
      span.ml-2 = personal_data.last_name

    div.flex.items-center
      strong.block.font-medium.mb-1 Nickname:
      span.ml-2 = personal_data.nick_name

    div.flex.items-center
      strong.block.font-medium.mb-1 Email:
      span.ml-2 = personal_data.email_address

    div.flex.items-center
      strong.block.font-medium.mb-1 Phone Number:
      span.ml-2 = personal_data.phone_number

    - if personal_data.employments.any?
      <div class="font-semibold text-lg mt-4">Employments:</div>
      table.w-full.mt-4
        thead.bg-green-100.border.px-8.py-4
          th Employer
          th Date Started
          th Date Ended
        tbody
          - personal_data.employments.each do |employment|
            tr.border.text-center.px-8.py-4
              td.border
                = employment.employer
              td.border
                = employment.date_started
              td.border
                = employment.date_ended

    - if action_name != "show"
      = link_to "Show this personal data", personal_data, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
      hr.mt-6

- if defined?(personal_info)
  .flex.justify-center.items-center.mt-28.mb-28
    table.w-full
      th.bg-green-100.border.px-8.py-4 First Name
      th.bg-green-100.border.px-8.py-4 Last Name
      th.bg-green-100.border.px-8.py-4 Nick Name
      th.bg-green-100.border.px-8.py-4 Email Address
      th.bg-green-100.border.px-8.py-4 Phone Number
      th.bg-green-100.border.px-8.py-4 Action
      tbody
        - personal_info.each do |data|
          tr.border.text-center.px-8.py-4
            td.border
              = data.first_name
            td.border
              = data.last_name
            td.border
              = data.nick_name
            td.border
              = data.email_address
            td.border
              = data.phone_number
            td.border
             a.underline.text-blue-500 href="/personal_data/#{data.id}"
              = 'Show'

app/views/personal_data/index.html.slim
.w-full
  .flex.flex-col.justify-center.items-center
    .mt-0.mb-auto
      = button_to 'Personal Data', new_personal_datum_path, method: :get, data: { turbo_frame: 'modal' }, class: "rounded-lg py-3 px-5 bg-green-600 text-white block font-medium"

- if @personalData.count > 0
  = render 'personal_data', personal_info: @personalData

app/views/personal_data/new.html.slim
= turbo_frame_tag "modal", data: { personal_data_id: @personalData.id }
  = tag.div data: { controller: "turbo-modal", turbo_modal_target: "modal", action: "turbo:keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" } do
    = render "form", personal_data: @personalData

app/views/personal_data/show.html.slim
<div class="text-center font-semibold text-2xl">Employee Details</div>
.mx-auto.md:w-1/3.mt-8
  .mx-auto
    = render @personalData
    .inline-block
    = link_to 'Back to personal data', root_path, class: "rounded-lg py-3 px-5 bg-green-100 inline-block font-medium mt-10"